version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PARTNER_SERVER_MONGODB_URI=mongodb://root:password@mongodb:27017
      - PARTNER_SERVER_MONGODB_DATABASE=gamedb
      - PARTNER_SERVER_REDIS_HOST=redis:6379
      - PARTNER_SERVER_REDIS_PASSWORD=
      - PARTNER_SERVER_REDIS_DB=0
      - PARTNER_SERVER_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - PARTNER_SERVER_JWT_SECRET_KEY=jwt-secret-key
      - PARTNER_SERVER_JWT_ACCESS_EXPIRY=1h
      - PARTNER_SERVER_JWT_REFRESH_EXPIRY=24h
    volumes:
      - ./config/config.example.yaml:/app/config/config.yaml:ro
      - ./config/firebase_credential.json:/app/config/firebase_credential.json:ro
    depends_on:
      - redis
      - mongodb

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb

volumes:
  redis_data:
  mongodb_data: 