server:
  host: localhost
  port: 8080

mongodb:
  uri: "mongodb://root:password@localhost:27017"
  database: "gamedb"

redis:
  host: localhost:6379
  password: 
  db: 0

firebase:
  project_id: "your-project-id"
  credential_file: "config/firebase_credential.json" 