package handler

import (
	"context"
	"net/http"
	"time"

	"github.com/Financial-Partner/server/internal/contextutil"
	"github.com/Financial-Partner/server/internal/entities"
	"github.com/Financial-Partner/server/internal/interfaces/http/dto"
	httperror "github.com/Financial-Partner/server/internal/interfaces/http/error"
	responde "github.com/Financial-Partner/server/internal/interfaces/http/respond"
)

//go:generate mockgen -source=report.go -destination=report_mock.go -package=handler

type ReportService interface {
	GetReport(ctx context.Context, userID string, startTime time.Time, endTime time.Time, reportType string) (*entities.Report, error)
	GetReportSummary(ctx context.Context, userID string) (*entities.ReportSummary, error)
}

// @Summary Get report
// @Description Get report for a user
// @Tags reports
// @Accept json
// @Produce json
// @Param Authorization header string true "Bearer {token}" default
// @Param type query string true "Type of report (summary or detailed)"
// @Param start query string false "Start date in YYYY-MM-DD format"
// @Param end query string false "End date in YYYY-MM-DD format"
// @Success 200 {object} dto.ReportResponse
// @Failure 400 {object} dto.ErrorResponse
// @Failure 401 {object} dto.ErrorResponse
// @Failure 500 {object} dto.ErrorResponse
// @Router /reports/finance [get]
func (h *Handler) GetReport(w http.ResponseWriter, r *http.Request) {
	// Parse query parameters
	reportType := r.URL.Query().Get("type")
	start := r.URL.Query().Get("start")
	end := r.URL.Query().Get("end")

	var startDate, endDate time.Time
	var err error
	if start != "" {
		startDate, err = time.Parse("2006-01-02", start)
		if err != nil {
			h.log.Warnf("Invalid start date format. Use YYYY-MM-DD.")
			responde.WithError(w, r, h.log, err, httperror.ErrInvalidParameter, http.StatusBadRequest)
			return
		}
	}
	if end != "" {
		endDate, err = time.Parse("2006-01-02", end)
		if err != nil {
			h.log.Warnf("Invalid end date format. Use YYYY-MM-DD.")
			responde.WithError(w, r, h.log, err, httperror.ErrInvalidParameter, http.StatusBadRequest)
			return
		}
	}

	userID, ok := contextutil.GetUserID(r.Context())
	if !ok {
		h.log.Warnf("failed to get user ID from context")
		responde.WithError(w, r, h.log, nil, httperror.ErrUnauthorized, http.StatusUnauthorized)
		return
	}

	report, err := h.reportService.GetReport(r.Context(), userID, startDate, endDate, reportType)
	if err != nil {
		h.log.Errorf("failed to get report")
		responde.WithError(w, r, h.log, err, httperror.ErrFailedToGetReport, http.StatusInternalServerError)
		return
	}

	resp := dto.ReportResponse{
		Revenue:     report.Revenue,
		Expenses:    report.Expenses,
		NetProfit:   report.NetProfit,
		Categorys:   report.Categorys,
		Amounts:     report.Amounts,
		Percentages: report.Percentages,
	}

	responde.WithJSON(w, r, resp, http.StatusOK)
}

// @Summary Get report summary
// @Description Get report summary generated by AI for a user
// @Tags reports
// @Accept json
// @Produce json
// @Param Authorization header string true "Bearer {token}" default
// @Success 200 {object} dto.ReportSummaryResponse
// @Failure 401 {object} dto.ErrorResponse
// @Failure 500 {object} dto.ErrorResponse
// @Router /reports/analysis [get]
func (h *Handler) GetReportSummary(w http.ResponseWriter, r *http.Request) {
	userID, ok := contextutil.GetUserID(r.Context())
	if !ok {
		h.log.Warnf("failed to get user ID from context")
		responde.WithError(w, r, h.log, nil, httperror.ErrUnauthorized, http.StatusUnauthorized)
		return
	}

	reportSummary, err := h.reportService.GetReportSummary(r.Context(), userID)
	if err != nil {
		h.log.Errorf("failed to get report summary")
		responde.WithError(w, r, h.log, err, httperror.ErrFailedToGetReportSummary, http.StatusInternalServerError)
		return
	}

	resp := dto.ReportSummaryResponse{
		Summary: reportSummary.Summary,
	}

	responde.WithJSON(w, r, resp, http.StatusOK)
}
